pipeline {
    agent any
    tools {
        jdk 'Jenkins-java17'
        nodejs 'node23'
        maven Jenkin-maven'
    }
    environment {
        SCANNER_HOME=tool 'sonar-scanner'
    }
    stages {
        stage ("clean workspace") {
            steps {
                cleanWs()
            }
        }
        
        stage ("sonar-qube analysis") {
            steps {
                withVault(configuration: [vaultCredentialId: "vault-sonar"],
                  vaultSecrets: [[path: "sonar/cred", engineVersion: 1, secretValues:[ [envVar: "SONAR_user", vaultKey: "username"],
                  [envVar: "SONAR_password", vaultKey: "password"]]]])
                  {
                    sh '''
                      $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=zomato \
                    -Dsonar.projectKey=zomato -Dsonar.login=${SONAR_TOKEN}
                    '''
                  
                  
                    script {
                        waitForQualityGate abortPipeline: false
                    }
                  }
            }
        }

        stage ( "Install NPM Dependencies") {
            steps {
                sh "npm install"
            }
        }
        stage ("snyk scan") {
            steps {
                withVault(configuration: [vaultCredentialId: "vault-snyk-role"],
                  vaultSecrets: [[path: "snyk/token", secretValues: [envVar: "SNYK_TOKEN", vaultKey: "token"]]])
                  {
                    sh '''
                      snyk test --all-projects --severity-threshold=high --json > snyk_report.json
                    '''
                  }
            }

        }

        stage ("Trivy File Scan") {
            steps {
                sh "trivy fs . > trivy.txt"
            }
        }

        stage ("Build Docker Image") {
            steps {
                sh "docker build -t http://172.31.47.157:8081/repository/docker-hosted:latest ."
            }
        }

        stage ("trivy image scan") {
            steps {
                sh "trivy image --exit-code 1 --severity HIGH,CRITICAL http://172.31.47.157:8081/repository/docker-hosted:latest"
            }
        }

        stage ("Publish Docker Image") {
            steps {
                withVault(configuration: [vaultCredentialId: "vault-approle"],
                  vaultSecrets: [[path: "jenkins/nexus", secretValues: [[envVar: "nexus_user", vaultkey: "username"],
                  [envVar: "nexus_password", vaultKey: "password"]]]])
                  {
                    sh '''
                      docker login http://172.31.47.157:8081 -u $nexus_user -p $nexus_password
                      docker push http://172.31.47.157:8081/repository/docker-hosted:latest
                    '''
                  }

            }
        }

        stage ("Deploy to Container") {
            steps {
                sh 'docker run -d --name zomato -p 3000:3000 http://172.31.47.157:8081/repository/docker-hosted:latest'
            }
        

          post {
            always {
              emailext attachLog: true,
                subject: "'${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: white; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: white; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                        <div style="background-color: #87CEEB; padding: 10px; margin-bottom: 10px;">
                            <p style="color: white; font-weight: bold;">URL: ${env.BUILD_URL}</p>
                        </div>
                    </body>
                    </html>
                """,
                to: 'naveentharapatla@gmail.com',
                mimeType: 'text/html',
                attachmentsPattern: 'trivy.txt'
            }
        }
    }
    }
}