pipeline {
    agent any
    tools {
        jdk 'Jenkins-java17'
        nodejs 'node23'
        maven 'Jenkin-maven'
    }
    environment {
        SCANNER_HOME=tool 'sonar-scanner'
    }
    stages {
        

        stage ("debug workspace") {
            steps {
                sh "ls -la"
                sh "pwd"
                sh 'find . -maxdepth 2 -type d'

                
            }
        }
        
        stage ("sonar-qube analysis") {
            steps {
                  withSonarQubeEnv('sonarserver') {

                    withVault(configuration: [vaultCredentialId: "vault-jenkins"],
                      vaultSecrets: [[path: "secret/sonar", engineVersion: 2, secretValues:[ [envVar: "SONAR_TOKEN", vaultKey: "token"],
                      ]]]) {
                  
                        sh '''
                          $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=zomato \
                         -Dsonar.projectKey=zomato -Dsonar.sources=. -Dsonar.login=${SONAR_TOKEN} 
                    '''
                  
                  
                    
                  }
            }
        }
        }

        

        

        stage ( "Install NPM Dependencies") {
            steps {
                sh '''
                  cd FoodAppZomato
                    npm install
                '''
            }
        }

        stage ("install snyk") {
            steps {
                sh '''
                  npm install -g snyk
                  snyk --version
                '''
            }
        }
        stage ("snyk scan") {
            steps {
                withVault(configuration: [vaultCredentialId: "vault-jenkins"],
                  vaultSecrets: [[path: "secret/snyk",engineVersion: 2, secretValues: [[envVar: "SNYK_TOKEN", vaultKey: "snyk-token"]]]])
                  {
                    sh '''
                      snyk auth ${SNYK_TOKEN}
                      snyk test --all-projects --severity-threshold=high --json > snyk_report.json || true
                    '''
                  }
            }

        }

        stage ("Trivy File Scan") {
            steps {
                sh "trivy fs . > trivy.txt"
            }
        }

        stage ("Build Docker Image") {
            steps {
                dir('FoodAppZomato') {

                  sh "docker build -t 172.31.47.157:8082/repository/docker-hosted:latest  ."

                }
            }
        }

        stage ("trivy image scan") {
            steps {
                sh "trivy image --exit-code 1 --severity HIGH,CRITICAL 172.31.47.157:8082/repository/docker-hosted:latest || true"
            }
        }

        stage ("Publish Docker Image") {
            steps {
                withVault(configuration: [vaultCredentialId: "vault-jenkins"],
                  vaultSecrets: [[path: "secret/nexus",engineVersion: 2, secretValues: [[envVar: "nexus_user", vaultKey: "username"],
                  [envVar: "nexus_password", vaultKey: "password"]]]])
                  {
                    sh '''
                      echo $nexus_password | docker login 172.31.47.157:8082 -u $nexus_user --password-stdin
                      docker push 172.31.47.157:8082/repository/docker-hosted/online-food:latest
                    '''
                  }

            }
        }

        stage ("Deploy to Container") {
            steps {
                sh 'docker run -d --name zomato -p 3000:3000 172.31.47.157:8082/repository/docker-hosted:latest'
            }
        

          post {
            always {
              emailext attachLog: true,
                subject: "'${currentBuild.result}'",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                            <p style="color: white; font-weight: bold;">Project: ${env.JOB_NAME}</p>
                        </div>
                        <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                            <p style="color: white; font-weight: bold;">Build Number: ${env.BUILD_NUMBER}</p>
                        </div>
                        <div style="background-color: #87CEEB; padding: 10px; margin-bottom: 10px;">
                            <p style="color: white; font-weight: bold;">URL: ${env.BUILD_URL}</p>
                        </div>
                    </body>
                    </html>
                """,
                to: 'naveentharapatla@gmail.com',
                mimeType: 'text/html',
                attachmentsPattern: 'trivy.txt'
            }
        }
    }
    }
}